import Container from "@/components/shared/layout/container"

const stats = [
  {
    value: "2.5M+",
    label: "Calories Burned",
    description: "Converted into productive farming activity",
  },
  {
    value: "15K+",
    label: "Urban Farmers",
    description: "Growing food from balconies and rooftops",
  },
  {
    value: "120 Tons",
    label: "Food Produced",
    description: "Fresh harvest generated by the community",
  },
  {
    value: "400+",
    label: "Communities",
    description: "Schools, NGOs and local groups involved",
  },
]

export default function KPISection() {
  return (
    <section className="relative py-32">
      <Container>
        <div className="mb-16 text-center">
          <h2 className="text-4xl font-black text-white md:text-6xl">
            Real Impact.
          </h2>

          <p className="mx-auto mt-6 max-w-3xl text-lg text-slate-400">
            Every crop planted contributes to healthier lifestyles,
            stronger communities and greener cities.
          </p>
        </div>

        <div className="grid gap-8 md:grid-cols-2 xl:grid-cols-4">
          {stats.map((stat) => (
            <div
              key={stat.label}
              className="
                group
                relative
                overflow-hidden
                rounded-3xl
                border
                border-white/10
                bg-white/[0.03]
                p-8
                backdrop-blur-xl
                transition-all
                duration-500
                hover:-translate-y-2
                hover:border-emerald-500/40
              "
            >
              <div
                className="
                  absolute
                  inset-0
                  opacity-0
                  transition
                  duration-500
                  group-hover:opacity-100
                  bg-gradient-to-br
                  from-emerald-500/10
                  to-cyan-500/10
                "
              />

              <div className="relative">
                <h3 className="text-5xl font-black text-white">
                  {stat.value}
                </h3>

                <p className="mt-4 text-xl font-semibold text-emerald-400">
                  {stat.label}
                </p>

                <p className="mt-3 text-sm leading-relaxed text-slate-400">
                  {stat.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </Container>
    </section>
  )
}